import Cookies from 'js-cookie';

export const createTempPlaylist = (spotifyUserID) => {
  const authToken = Cookies.get('spotifyAuthToken');
  fetch(`https://api.spotify.com/v1/users/${spotifyUserID}/playlists`, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: {
      name: 'Soundtrip Temp Playlist',
      description:
        'This is your temporary playlist generated by Soundtrip.app. This playlist will dissappear when you logout of Soundtrip.',
      public: false,
    },
  })
    .then((response) => response.json())
    .then((data) => {
      console.log('Success:', data);
    })
    .catch((error) => {
      console.error('Error:', error);
    });
};
