import Cookies from 'js-cookie';

export const createTempPlaylist = (spotifyUserID) => {
  const authToken = Cookies.get('spotifyAuthToken');
  fetch(`https://api.spotify.com/v1/users/${spotifyUserID}/playlists`, {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
    body: JSON.stringify({
      name: 'Soundtrip Temp Playlist',
      description:
        'This is your temporary playlist generated by Soundtrip.app. This playlist will dissappear when you logout of Soundtrip.',
      public: false,
    }),
  })
    .then((response) => response.json())
    .then((data) => {
      console.log('Success:', data);
      console.log('playlist ID,', data.id);
      Cookies.set('tempPlaylistID', data.id);
    })
    .then(() => {
      console.log('Success:', Cookies.get());
    })
    .catch((error) => {
      console.error('Error:', error);
    });
};

export const deleteTempPlaylist = (playlist_id) => {
  const authToken = Cookies.get('spotifyAuthToken');
  fetch(`https://api.spotify.com/v1/playlists/${playlist_id}/followers`, {
    method: 'DELETE',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
      Authorization: `Bearer ${authToken}`,
    },
  })
    .then(() => {
      console.log('Success: playlist deleted');
    })
    .catch((error) => {
      console.error('Error:', error);
    });
};
